apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: drehnstrom/events-internal-deloitte:v1.0
        env: 
        - name: roidtc-march406
          value: "mar-roidtc400-instructor"
        ports:
        - containerPort: 8082
            
        
